### PR TITLE
fix: fix broken lr

### LINKED ISSUE #143: Convert result for `\left\lbrack\lbrack x\rbrack\right\rbrack` is broken
```tex
\left\lbrack\lbrack x\rbrack\right\rbrack
```

becomes

```typ
lr(bracket.lbracket.l  x bracket.r bracket.r)
```

Note the consecutive bracket.l, this triggers compile error.

related: https://github.com/OI-wiki/OI-wiki/pull/5475

### PR DESCRIPTION
**Pull request by OrangeX4**
fix #143

### CODE REVIEW

File: crates/mitex/src/lib.rs [hunk 1]
```diff
@@ -949,29 +951,35 @@ mod tests {
...
         assert_debug_snapshot!(convert_math(r#"$\left.a\right.$"#), @r###"
         Ok(
-            "lr(a )",
+            "lr( a  )",
         )
         "###);
         assert_debug_snapshot!(convert_math(r#"$\alpha\left.\right.$"#), @r###"
         Ok(
-            "alpha lr()",
+            "alpha lr(  )",
```
Comment (Enter-tainer) [inline crates/mitex/src/lib.rs:964]: what does this looks like?

Comment (Enter-tainer) [reply crates/mitex/src/lib.rs:964]: It would be better if we have snapshot test in svg/png so we can be more confident about convert result 🤔

Comment (Enter-tainer) [reply crates/mitex/src/lib.rs:964]: https://github.com/Enter-tainer/typstyle/blob/6b287661f63a6ec8d8b147e3d99682949634a5bb/tests/assets.rs#L162

Comment (Enter-tainer) [reply crates/mitex/src/lib.rs:964]: I test it locally and they are the same. We may convert this into a issue

**Review by Enter-tainer — APPROVED** [review]
ty!
